import { ORUI } from "../base/index.js";
export function ButtonDemo() {
    const html = (ORUI.createElement("orui-grid", null,
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "block\u6309\u94AE" },
                ORUI.createElement("orui-button", { text: "test\u6309\u94AE", block: "1", type: "fill", size: "large", onClick: (ev) => { console.log(ev); } }))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "\u4E0D\u540C\u5C3A\u5BF8\u7684\u6309\u94AE" },
                ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                    ORUI.createElement("orui-button", { text: "mini", type: "fill", color: "default", size: "mini" }),
                    ORUI.createElement("orui-button", { text: "small", type: "fill", color: "default", size: "small" }),
                    ORUI.createElement("orui-button", { text: "normal", type: "fill", color: "default" }),
                    ORUI.createElement("orui-button", { text: "large", type: "fill", color: "default", size: "large" })))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "\u4E0D\u540C\u989C\u8272fill\u7684\u6309\u94AE" },
                ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                    ORUI.createElement("orui-button", { text: "primary", type: "fill", color: "primary" }),
                    ORUI.createElement("orui-button", { text: "danger", type: "fill", color: "danger" }),
                    ORUI.createElement("orui-button", { text: "success", type: "fill", color: "success" }),
                    ORUI.createElement("orui-button", { text: "warning", type: "fill", color: "warning" })))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "\u4E0D\u540C\u989C\u8272outline\u7684\u6309\u94AE" },
                ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", color: "default" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", color: "primary" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", color: "danger" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", color: "success" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", color: "warning" })))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "\u4E0D\u540C\u989C\u8272\u7684\u4E0D\u5E26\u8FB9\u6846\u6309\u94AE" },
                ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", color: "default", id: "test" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", color: "primary" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", color: "danger" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", color: "success" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", color: "warning" })))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "\u5E26icon\u6309\u94AE" },
                ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "fill", size: "mini", color: "primary", id: "test", icon: "/components/images/search.svg" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "fill", size: "small", color: "primary", id: "test", icon: "/components/images/search.svg" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "fill", size: "normal", color: "primary", id: "test", icon: "/components/images/search.svg" }),
                    ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "fill", size: "large", color: "primary", id: "test", icon: "/components/images/search.svg" })))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-space", { align: "center", wrap: "1" },
                ORUI.createElement("orui-title", { text: "icon\u4F4D\u7F6E\u81EA\u5B9A\u4E49" },
                    ORUI.createElement("orui-space", null,
                        ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "outline", size: "mini", color: "default", id: "test", icon: "/components/images/search.svg", icon_align: "right" }),
                        ORUI.createElement("orui-button", { text: "", type: "outline", size: "mini", color: "default", icon: "/components/images/search.svg", icon_align: "center" }),
                        ORUI.createElement("orui-button", { text: "", type: "outline", size: "mini", color: "default", icon: "/components/images/search.svg", icon_align: "center" }))),
                ORUI.createElement("orui-title", { text: "\u81EA\u5B9A\u4E49font-weight" },
                    ORUI.createElement("orui-space", null,
                        ORUI.createElement("orui-button", { text: "test\u6309\u94AE", type: "none", size: "mini", color: "primary", custom_style: "--font-weight: bold" }))))),
        ORUI.createElement("orui-row", { grow: "0" },
            ORUI.createElement("orui-title", { text: "disabled" },
                ORUI.createElement("orui-button", { text: "test\u6309\u94AE", disable: "true" })))));
    return html;
}
