import "./svg-inject.min.js";
import "./icon/index.js";
import "/components/button/index.js";
import "/components/input/index.js";
import "/components/tab/index.js";
import "/components/space/index.js"
import "/components/template/index.js"
import "/components/grid/index.js"
import "/components/row/index.js"
import "/components/col/index.js"
import "/components/list/index.js";
import "/components/listItem/index.js";
import "/components/radio/index.js";
import "/components/searchBar/index.js";
import "/components/title/index.js";
import "/components/pullToRefresh/index.js";
import "/components/slider/index.js";
import "/components/popup/index.js";
import "/components/mask/index.js";
import "/components/selector/index.js";
import "/components/stepper/index.js";
import "/components/scrollBar/index.js";
import "/components/pickerView/index.js";
import "/components/form/index.js";
import "/components/formItem/index.js";
import "/components/cascadePickerView/index.js";
import "/components/datePickerView/index.js";
import "/components/picker/index.js";
import "/components/datePicker/index.js";
import "/components/cascadePicker/index.js";
import "/components/tabBar/index.js";
import "/components/navBar/index.js";
import "/components/progressBar/index.js";
import "/components/divider/index.js";
import "/components/swipeAction/index.js";
import "/components/toast/index.js";
import "/components/dialog/index.js";
import "/components/checkList/index.js";
import "/components/dropdown/index.js";
import '/components/router/index.js';
import '/components/layout/index.js';
import '/components/page/index.js';
import '/components/cache/index.js';
